[package]
name = "scroll"
version = "0.1.0"
authors = ["m4b <m4b.github.io@gmail.com>"]
readme = "README.md"
keywords = ["bytes", "buffer", "scroll", "fun", "immutable"]
repository = "https://github.com/m4b/scroll"
license = "MIT"
description = "Putting the lol back in scroll since 2016"

[dependencies]
